/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const isEven = (val) => {
	if(val % 2 === 0) {
		return true;
	}

	return false;
}

const EvenFiboSumUnderX = (x) => {
	let arr = [1,2];
	let evenSum = 2;
	let nextVal = 0;

	for(let i = 1; arr[i] < x; i++) {
		nextVal = arr[i] + arr[i-1];
		arr.push(nextVal);

		if(isEven(nextVal) && nextVal < x) {
			evenSum += nextVal;
		}
	}

	return evenSum;
}

console.log(EvenFiboSumUnderX(4000000));
